# Все используемые классом домены
["Используемые домены"]

    [["Домен"]]
        "Мнемокод" = "TCOMPANY"
        "Наименование (RU)" = "Организация"
        "Наименование (UK)" = "Організація"
        "Тип данных" = "Число"
        "Подтип данных" = "Простое число"
        "Точность данных" = 17
        "Дробность данных" = 0
        "Выравнивать по длине" = false
        "Имеет перечисляемые значения" = false

    [["Домен"]]
        "Мнемокод" = "TCRN"
        "Наименование (RU)" = "Каталог"
        "Наименование (UK)" = "Каталог"
        "Тип данных" = "Число"
        "Подтип данных" = "Простое число"
        "Точность данных" = 17
        "Дробность данных" = 0
        "Выравнивать по длине" = false
        "Имеет перечисляемые значения" = false

    [["Домен"]]
        "Мнемокод" = "TGUID"
        "Наименование (RU)" = "GUID (Строка 36)"
        "Наименование (UK)" = "Ідентифікатор"
        "Тип данных" = "Строка"
        "Подтип данных" = "Простая строка"
        "Размер строки" = 36
        "Выравнивать по длине" = false
        "Имеет перечисляемые значения" = false

    [["Домен"]]
        "Мнемокод" = "TNUMB06.00 DEF 0"
        "Наименование (RU)" = "Число 06.00 (По умолчанию 0)"
        "Наименование (UK)" = "Число 06.00 (По умолчанию 0)"
        "Тип данных" = "Число"
        "Подтип данных" = "Простое число"
        "Точность данных" = 6
        "Дробность данных" = 0
        "Значение по умолчанию" = 0
        "Выравнивать по длине" = false
        "Имеет перечисляемые значения" = false

    [["Домен"]]
        "Мнемокод" = "TRN"
        "Наименование (RU)" = "Регистрационный номер"
        "Наименование (UK)" = "Реєстраційний номер"
        "Тип данных" = "Число"
        "Подтип данных" = "Простое число"
        "Точность данных" = 17
        "Дробность данных" = 0
        "Выравнивать по длине" = false
        "Имеет перечисляемые значения" = false
# Метаданные класса

["Класс"]
    "Код" = "UdoFileStoreFolders"
    "Наименование (RU)" = "Места хранения присоединенных файлов (папки)"
    "Наименование (UK)" = "Місця зберігання приєднаних файлів (папки)"
    "Абстрактный" = false
    ["Таблица"]
        "Имя" = "UDO_FILEFOLDERS"
        "Наименование (RU)" = "Места хранения файлов (папки)"
        "Наименование (UK)" = "Місця зберігання файлів (папки)"
        "Тип информации" = "Постоянная"
        "Технология производства" = "Конструктор"
    "Буферный" = false
    "Ведомый" = false
    "Деление" = "По организациям"
    "Юридические лица" = false
    "Иерархия" = false
    "Каталоги" = true
    "Свойства документов" = false
    "Присоединенные документы" = false
# Атрибуты класса
    ["Класс.Атрибуты"]

        [["Класс.Атрибут"]]
            "Имя" = "RN"
            "Наименование (RU)" = "Регистрационный  номер"
            "Наименование (UK)" = "Реєстраційний номер"
            "Позиция" = 1
            "Тип" = "Физический"
            "Домен" = "TRN"

        [["Класс.Атрибут"]]
            "Имя" = "COMPANY"
            "Наименование (RU)" = "Организация  (ссылка на COMPANIES(RN))"
            "Наименование (UK)" = "Організація"
            "Позиция" = 2
            "Тип" = "Физический"
            "Домен" = "TCOMPANY"

        [["Класс.Атрибут"]]
            "Имя" = "CRN"
            "Наименование (RU)" = "Каталог  (ссылка на ACATALOG(RN))"
            "Наименование (UK)" = "Каталог (посилання на ACATALOG (RN))"
            "Позиция" = 3
            "Тип" = "Физический"
            "Домен" = "TCRN"

        [["Класс.Атрибут"]]
            "Имя" = "PRN"
            "Наименование (RU)" = "Регистрационный номер родительской записи"
            "Наименование (UK)" = "Реєстраційний номер батьківського запису"
            "Позиция" = 4
            "Тип" = "Физический"
            "Домен" = "TRN"

        [["Класс.Атрибут"]]
            "Имя" = "NAME"
            "Наименование (RU)" = "Наименование папки"
            "Наименование (UK)" = "Найменування папки"
            "Позиция" = 5
            "Тип" = "Физический"
            "Домен" = "TGUID"

        [["Класс.Атрибут"]]
            "Имя" = "FILECNT"
            "Наименование (RU)" = "Количество файлов в папке"
            "Наименование (UK)" = "Кількість файлів в папці"
            "Позиция" = 6
            "Тип" = "Физический"
            "Домен" = "TNUMB06.00 DEF 0"
# Ограничения класса
    ["Класс.Ограничения"]

        [["Ограничение"]]
            "Имя" = "UDO_C_FILEFOLDERS_NAME_UK"
            "Наименование (RU)" = "Уникальность наименования"
            "Наименование (UK)" = "Унікальність найменування"
            "Тип" = "Уникальность"
            "Использовать для разрешения ссылок" = false
            ["Ограничение.Сообщение при нарушениии"]
                "Мнемокод" = "UDO_C_FILEFOLDERS_NAME_UK"
                "Технология производства" = "Конструктор"
                "Тип" = "Сообщение ограничения"
                "Текст (RU)" = "Дублирование наименования раздела  «Места хранения присоединенных файлов (папки)»."
            ["Класс.Ограничения.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут" = "PRN"

                [["Атрибут"]]
                    "Позиция" = 2
                    "Атрибут" = "NAME"

        [["Ограничение"]]
            "Имя" = "UDO_C_FILEFOLDERS_PK"
            "Наименование (RU)" = "Первичный ключ раздела"
            "Наименование (UK)" = "Первинний ключ розділу"
            "Тип" = "Первичный ключ"
            "Использовать для разрешения ссылок" = false
            ["Ограничение.Сообщение при нарушениии"]
                "Мнемокод" = "UDO_C_FILEFOLDERS_PK"
                "Технология производства" = "Конструктор"
                "Тип" = "Сообщение ограничения"
                "Текст (RU)" = "Дублирование регистрационного номера «Места хранения присоединенных файлов (папки)»"
            ["Класс.Ограничения.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут" = "RN"

        [["Ограничение"]]
            "Имя" = "UDO_C_FILEFOLDERS_FILECNT_VAL"
            "Наименование (RU)" = "Условие на значение количество файлов в папке места хранения присоединенных файлов (папки)"
            "Наименование (UK)" = "Условие на значение количество файлов в папке места хранения присоединенных файлов (папки)"
            "Тип" = "Проверка"
            "Использовать для разрешения ссылок" = false
            "Текст ограничения" = "FILECNT >= 0"
            ["Ограничение.Сообщение при нарушениии"]
                "Мнемокод" = "UDO_C_FILEFOLDERS_FILECNT_VAL"
                "Технология производства" = "Конструктор"
                "Тип" = "Сообщение ограничения"
                "Текст (RU)" = "Значение количество файлов в папке места хранения присоединенных файлов (папки) не удовлетворяет условию."
            ["Класс.Ограничения.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут" = "FILECNT"

        [["Ограничение"]]
            "Имя" = "UDO_C_FILEFOLDERS_NAME_NB"
            "Наименование (RU)" = "Непустое наименование"
            "Наименование (UK)" = "Непусте найменування"
            "Тип" = "Проверка"
            "Использовать для разрешения ссылок" = false
            "Текст ограничения" = "RTRIM(NAME) IS NOT NULL"
            ["Ограничение.Сообщение при нарушениии"]
                "Мнемокод" = "UDO_C_FILEFOLDERS_NAME_NB"
                "Технология производства" = "Конструктор"
                "Тип" = "Сообщение ограничения"
                "Текст (RU)" = "Наименование не может состоять только из пробелов."
            ["Класс.Ограничения.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут" = "NAME"

        [["Ограничение"]]
            "Имя" = "C_UDO_FILEFOLDERS_ALLNN"
            "Наименование (RU)" = "Обязательные атрибуты"
            "Наименование (UK)" = "Обов'язкові атрибути"
            "Тип" = "Обязательность"
            "Использовать для разрешения ссылок" = false
            ["Ограничение.Сообщение при нарушениии"]
                "Мнемокод" = "C_SYSTEM_NOTNULL"
                "Технология производства" = "Конструктор"
                "Тип" = "Сообщение ограничения"
                "Текст (RU)" = "Поле обязательное."
            ["Класс.Ограничения.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут" = "RN"

                [["Атрибут"]]
                    "Позиция" = 3
                    "Атрибут" = "COMPANY"

                [["Атрибут"]]
                    "Позиция" = 4
                    "Атрибут" = "CRN"

                [["Атрибут"]]
                    "Позиция" = 5
                    "Атрибут" = "PRN"

                [["Атрибут"]]
                    "Позиция" = 6
                    "Атрибут" = "NAME"

                [["Атрибут"]]
                    "Позиция" = 7
                    "Атрибут" = "FILECNT"

        [["Ограничение"]]
            "Имя" = "C_UDO_FILEFOLDERS_NOTCH"
            "Наименование (RU)" = "Неизменяемые атрибуты"
            "Наименование (UK)" = "Незмінні атрибути"
            "Тип" = "Неизменяемость"
            "Использовать для разрешения ссылок" = false
            ["Ограничение.Сообщение при нарушениии"]
                "Мнемокод" = "C_SYSTEM_NOTCHANGE"
                "Технология производства" = "Конструктор"
                "Тип" = "Сообщение ограничения"
                "Текст (RU)" = "Изменились неизменяемые поля."
            ["Класс.Ограничения.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут" = "RN"

                [["Атрибут"]]
                    "Позиция" = 3
                    "Атрибут" = "COMPANY"

                [["Атрибут"]]
                    "Позиция" = 5
                    "Атрибут" = "PRN"
# Связи класса
    ["Класс.Связи"]

        [["Связь"]]
            "Код" = "UDO_C_FILEFOLDERS_COMPANY_FK"
            "Наименование (RU)" = "Ссылка на «Организации»"
            "Наименование (UK)" = "Посилання на «Організації»"
            "Класс-источник" = "Companies"
            "Стереотип" = "Связь с организациями"
            "Физическая связь" = true
            "Ограничение класса-источника" = "C_COMPANIES_PK"
            "Правило" = "Нет правил"
            ["Класс.Связи.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут класса-приемника" = "COMPANY"
                    "Атрибут класса-источника" = "RN"

        [["Связь"]]
            "Код" = "UDO_C_FILEFOLDERS_CRN_FK"
            "Наименование (RU)" = "Ссылка на «Каталоги иерархии»"
            "Наименование (UK)" = "Посилання на «Каталоги ієрархії»"
            "Класс-источник" = "CatalogTree"
            "Стереотип" = "Связь с каталогами"
            "Физическая связь" = true
            "Ограничение класса-источника" = "C_ACATALOG_PK"
            "Правило" = "Нет правил"
            ["Класс.Связи.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут класса-приемника" = "CRN"
                    "Атрибут класса-источника" = "RN"

        [["Связь"]]
            "Код" = "UDO_C_FILEFOLDERS_PRN_FK"
            "Наименование (RU)" = "Ссылка на родителя"
            "Наименование (UK)" = "Посилання на батьківський запис"
            "Класс-источник" = "UdoFileStores"
            "Стереотип" = "Master-Detail"
            "Физическая связь" = true
            "Ограничение класса-источника" = "UDO_C_FILESTORES_PK"
            "Правило" = "Каскадное удаление"
            ["Класс.Связи.Атрибуты"]

                [["Атрибут"]]
                    "Позиция" = 1
                    "Атрибут класса-приемника" = "PRN"
                    "Атрибут класса-источника" = "RN"
# Представления класса
    ["Класс.Представления"]

        [["Представление"]]
            "Имя" = "UDO_V_FILEFOLDERS"
            "Наименование (RU)" = "Места хранения присоединенных файлов (папки) (клиентское представление)"
            "Наименование (UK)" = "Місця зберігання приєднаних файлів (папки) (Клієнтське представлення)"
            "Тип" = "Представление"
            "Вызывается с клиента" = true
            ["Класс.Представления.Атрибуты"]

                [["Атрибут"]]
                    "Атрибут класса" = "RN"
                    "Имя колонки" = "NRN"

                [["Атрибут"]]
                    "Атрибут класса" = "COMPANY"
                    "Имя колонки" = "NCOMPANY"

                [["Атрибут"]]
                    "Атрибут класса" = "CRN"
                    "Имя колонки" = "NCRN"

                [["Атрибут"]]
                    "Атрибут класса" = "PRN"
                    "Имя колонки" = "NPRN"

                [["Атрибут"]]
                    "Атрибут класса" = "NAME"
                    "Имя колонки" = "SNAME"

                [["Атрибут"]]
                    "Атрибут класса" = "FILECNT"
                    "Имя колонки" = "NFILECNT"
            ["Класс.Представления.Параметры"]
# Методы класса
    ["Класс.Методы"]
# Методы вызова
    ["Класс.Методы вызова"]

        [["Метод вызова"]]
            "Мнемокод" = "UserDefinedMethod"
            "Наименование (RU)" = "Вызов в качестве словаря через интерфейс конструкторских разделов"
            "Наименование (UK)" = "Виклик у якості словника через інтерфейс розділів користувача"
            "Технология производства" = "Конструктор"
            "Тип условий отбора" = "Клиент"
            "Использовать для отображения по умолчанию" = false
            "Использовать для отображения через связи документов" = false
            "Использовать для отображения в качестве словаря" = false
            ["Класс.Методы вызова.Параметры"]
            ["Класс.Методы вызова.Формы"]
# Действия
    ["Класс.Действия"]
# Объекты
    ["Класс.Объекты"]

        [["Объект"]]
            "Тип" = "Таблица"
            "Имя" = "UDO_FILEFOLDERS"
            "Наименование (RU)" = "Места хранения файлов (папки)"
            "Наименование (UK)" = "Місця зберігання файлів (папки)"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_FILEFOLDERS.sql"

        [["Объект"]]
            "Тип" = "Внешние ключи"
            "Имя" = "UDO_FILEFOLDERS_FK"
            "Наименование (RU)" = "Блок внешних ключей"
            "Наименование (UK)" = "Блок зовнішніх ключів"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_FILEFOLDERS_FK.sql"

        [["Объект"]]
            "Тип" = "Процедура"
            "Имя" = "UDO_P_FILEFOLDERS_BASE_DELETE"
            "Наименование (RU)" = "Базовое удаление"
            "Наименование (UK)" = "Базовое видалення"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_P_FILEFOLDERS_BASE_DELETE.prc"

        [["Объект"]]
            "Тип" = "Процедура"
            "Имя" = "UDO_P_FILEFOLDERS_BASE_INSERT"
            "Наименование (RU)" = "Базовое добавление"
            "Наименование (UK)" = "Базовое додавання"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_P_FILEFOLDERS_BASE_INSERT.prc"

        [["Объект"]]
            "Тип" = "Процедура"
            "Имя" = "UDO_P_FILEFOLDERS_BASE_UPDATE"
            "Наименование (RU)" = "Базовое исправление"
            "Наименование (UK)" = "Базовое виправлення"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_P_FILEFOLDERS_BASE_UPDATE.prc"

        [["Объект"]]
            "Тип" = "Процедура"
            "Имя" = "UDO_P_FILEFOLDERS_EXISTS"
            "Наименование (RU)" = "Считывание записи"
            "Наименование (UK)" = "Зчитування запису"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_P_FILEFOLDERS_EXISTS.prc"

        [["Объект"]]
            "Тип" = "Триггер"
            "Имя" = "UDO_T_FILEFOLDERS_ADELETE"
            "Наименование (RU)" = "Триггер после удаления"
            "Наименование (UK)" = "Тригер після видалення"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_T_FILEFOLDERS_ADELETE.trg"

        [["Объект"]]
            "Тип" = "Триггер"
            "Имя" = "UDO_T_FILEFOLDERS_BDELETE"
            "Наименование (RU)" = "Триггер до удаления"
            "Наименование (UK)" = "Тригер до видалення"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_T_FILEFOLDERS_BDELETE.trg"

        [["Объект"]]
            "Тип" = "Триггер"
            "Имя" = "UDO_T_FILEFOLDERS_BINSERT"
            "Наименование (RU)" = "Триггер до добавления"
            "Наименование (UK)" = "Тригер до додавання"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_T_FILEFOLDERS_BINSERT.trg"

        [["Объект"]]
            "Тип" = "Триггер"
            "Имя" = "UDO_T_FILEFOLDERS_BUPDATE"
            "Наименование (RU)" = "Триггер до исправления"
            "Наименование (UK)" = "Тригер до виправлення"
            "Вид" = "Базовый"
            "Исходный текст" = "Object_UDO_T_FILEFOLDERS_BUPDATE.trg"

        [["Объект"]]
            "Тип" = "Представление"
            "Имя" = "UDO_V_FILEFOLDERS"
            "Наименование (RU)" = "Места хранения присоединенных файлов (папки) (клиентское представление)"
            "Наименование (UK)" = "Місця зберігання приєднаних файлів (папки) (Клієнтське представлення)"
            "Вид" = "Клиентский"
            "Исходный текст" = "Object_UDO_V_FILEFOLDERS.vw"